### ISSUE TITLE
ULS Language list: remove the map

### ISSUE THREAD

**Issue by santhoshtr** [wikimedia/jquery.uls#128]
In recent observations(user testing) @pauginer noticed that the map entry point is not used at all when selecting languages and I was considering to recommend removing the map given that:

* "Suggested languages" and search work really well, and they seem to be enough.
* It will help to reduce the footprint and code to be maintained (e.g., hovering the map makes surrounding elements to move slightly, which will require also time for fixing if the map stays).
* A compact version is already available (as extra CSS rules that hide the map) since it is needed for other contexts. Having the current CSS for the compact version is expected to simplify the refactoring, and will avoid having to deal with two slightly different versions. In addition, the compact version worked well when testing the prototypes for compact links
* At some point, it may be interesting to do some update for the CSS to apply new agora styles.

**Comment by nemobis** [comment]
Was fixed in 2014, please close.
