### ISSUE TITLE
nl (Nederlands) is not listed in Europe section

### ISSUE THREAD

**Issue by liangent** [wikimedia/jquery.uls#204]
![wikipedia](https://cloud.githubusercontent.com/assets/198991/11790836/ccf4f170-a26b-11e5-9f73-b67498b3bb9e.png)

It's listed in American section instead. data/langdb.yaml lists it as [EU, AM] so I expect it to show up in both.

**Comment by santhoshtr** [comment]
You are supposed to see more columns there. Strangely your screenshot shown only one column

I see this
 ![image](https://cloud.githubusercontent.com/assets/161672/11807182/3f989e20-a33e-11e5-9387-9f64da77bab7.png)

**Comment by santhoshtr** [comment]
If you are not searching, Nederlands is not listed in Europe. strange

![image](https://cloud.githubusercontent.com/assets/161672/11807312/1a84ba96-a33f-11e5-8a86-d79d5293032e.png)

**Comment by nemobis** [comment]
Can we track this in the ULS component? https://phabricator.wikimedia.org/T117196

**Comment by Nikerabbit** [comment]
Fixed by #234.
