### ISSUE TITLE
Create a language data library out of jquery.uls.data module and make it independent of jquery

### ISSUE THREAD

**Issue by santhoshtr** [wikimedia/jquery.uls#206]
As written in https://phabricator.wikimedia.org/T131140

> The jquery.uls library provides jquery.uls.data which is a collection of language related data - script, direction, autonym, geographical information and a set of utility methods to look up this data. This was originally developed as part of ULS project and now widely used across many projects in WIkimedia.
> I think it does not need to be a jquery dependent library, and should be usable even with nodejs and all. The Language selector can add it as a dependency.

**Comment by Nikerabbit** [comment]
There is now a JSON file that can easily be reused in many programming languages. Should be easy to create a new project and move this part there.

**Comment by santhoshtr** [comment]
Closing as we have https://github.com/wikimedia/language-data
