### ISSUE TITLE
Add a 'default' language option to allow users to return to the original page language 

### ISSUE THREAD

**Issue by planemad** [wikimedia/jquery.uls#327]
User story:

A a viewer of a multilingual world map, I use the ULS to switch the language to my native language. I would like to return to the multilingual mode to explore the map but the ULS forces me to pick a single language and does not allow me to go back to the original map.

![new1](https://user-images.githubusercontent.com/126868/46922178-d709a880-d022-11e8-8111-6444814eef30.gif)
_multingual(original)->English->Chinese with no mechanism to return to the original mode [jsfiddle](https://jsfiddle.net/planemad/3rcdxb72/3/)_

Adding an option of a 'Default' language that can be used to return to the original setting can allow the ULS to be used on content that is multilingual by default.

**Comment by Nikerabbit** [comment]
You can do this already by injecting new language codes. Example:
https://github.com/wikimedia/mediawiki-extensions-Translate/blob/a5bc51f46d64cea97844a54ad18e859d84124dac/resources/js/ext.translate.base.js#L146
https://github.com/wikimedia/mediawiki-extensions-Translate/blob/6f191f4304598580f45d1e86b5e52405af239f77/resources/js/ext.translate.special.translate.js#L220

**Comment by planemad** [comment]
@Nikerabbit thanks, that works!
