### ISSUE TITLE
Please add Nias language

### ISSUE THREAD

**Issue by sslaia** [wikimedia/jquery.uls#430]
I see that Nias language is not in the list. Please provided support for Nias language (nia.wikipedia.org) or would you guide me how to add it (which files need to be modified?). Thanks.

**Comment by amire80** [comment]
It is definitely in the list. What exactly are you trying to do?

**Comment by sslaia** [comment]
The Nias language is missing from the language selection when I tried this [conze.pt](conze.pt) app, that aggregates the available languages from jquery.uls. The maintainer asked me to "request Nia language support here: https://github.com/wikimedia/jquery.uls/tree/master/i18n (this library is used in Conzept for the language selections)"
If this was already done here, I apologise.

BTW I don't see nia in the i18n folder.

**Comment by amire80** [comment]
Oh, this is interesting! The language does appear there. If I go to that website, click the language name at the top and type "li niha", then this language appears in the list. How did you search for it?

**Comment by sslaia** [comment]
Still can't find it there on conze.pt. If I click the language dropdown menu (where arrow English is) there is no Li Niha in the list. I can see other languages from Indonesia such Aceh, Java, Sunda etc. but not Nias.

**Comment by amire80** [comment]
This is really strange. Can you type "li niha" in the search box and take a screenshot?

I do see it:
![Screenshot_20220723-115628_Firefox](https://user-images.githubusercontent.com/346271/180598181-394031a1-fe7f-4426-ba4f-da66c4db70cc.jpg)

**Comment by sslaia** [comment]
You're right. I just tried it on mobile and it works. Unfortunately I'm out so I can't check again on my desktop. Let's hope everything works now.

**Comment by sslaia** [comment]
I tried it and the issue still occurs in Chrome browser. Nias would not show up in the list (see the picture below). But in Firefox it works just fine. So this is Chrome issue, then. Should I close this issue or leave it opened until somebody looks at it?
![image](https://user-images.githubusercontent.com/44895234/180619852-15b49f15-5997-4560-996f-b33de3d72d9f.png)

**Comment by waldenn** [comment]
> Oh, this is interesting! The language does appear there. If I go to that website, click the language name at the top and type "li niha", then this language appears in the list. How did you search for it?

Hi! I added the Nia language manually (as a temporary hack) to the ULS sources, but it also needs to be added upstream. Great project btw, thank you!

**Comment by waldenn** [comment]
> 


> I tried it and the issue still occurs in Chrome browser. Nias would not show up in the list (see the picture below). But in Firefox it works just fine. So this is Chrome issue, then. Should I close this issue or leave it opened until somebody looks at it?

Could you try a hard refresh (using CTRL-r), I think that should fix it. Chrome has very aggressive asset caching.

**Comment by sslaia** [comment]
> Could you try a hard refresh (using CTRL-r), I think that should fix it. Chrome has very aggressive asset caching.

Thanks. This solved the issue with Chrome.

**Comment by waldenn** [comment]
> 

Great. Closing the issue is normally done _after_ the issue (adding the Nias language to the code) has been implemented. This allows developers to see what needs to be done. So please open the issue again.

**Comment by sslaia** [comment]
> Closing the issue is normally done _after_ the issue (adding the Nias language to the code) has been implemented. This allows developers to see what needs to be done. So please open the issue again.

Done.

**Comment by amire80** [comment]
> Hi! I added the Nia language manually (as a temporary hack) to "src/jquery.uls.data.js" for Conzept, but it also needs to be added upstream,

It has been there for a long time: https://github.com/wikimedia/jquery.uls/blame/master/src/jquery.uls.data.js#L2853

> including the "nia.json" i18n file.

This is not necessary for the appearance of the language in the list. The i18n/*.json files are for the localization of the user interface. This was done for Nias yesterday in translatewiki.net, and soon it will be semi-automatically copied into the GitHub repo here.

> Great project btw, thank you!

You're welcome, and thank you for using jquery.uls! :)

**Comment by sslaia** [comment]
Sorry for my confusion. I understand that everything is set up as @amire80 said and this case should be closed. Thank you for your patience with me.
